### ISSUE TITLE
integration with nvidia Jarvis/ Riva framework

### ISSUE THREAD

**Issue by AndreV84** [frankkramer-lab/GERNERMED#1]
could you share some directions how to integrate with Nvidia ecosystem, please?
ref. https://forums.developer.nvidia.com/t/building-transcription-and-entity-recognition-apps-using-nvidia-jarvis/169442/10

**Comment by j-frei** [comment]
Hello @AndreV84,

I apologize for answering late to your request. Somehow my GitHub notification settings are messed up. (Just add @j-frei to trigger a mail notification for these purposes.)

As a short note: If you are interested in applying the model rather than "just" out of scientific curiosity, I'd like to point to our follow-up work, GERNERMED++:
GitHub: https://github.com/frankkramer-lab/GERNERMED-pp
ArXiv: https://arxiv.org/abs/2206.14504
The models perform significantly better so there is no advantage to stick with the initial GERNERMED model.

We also published the models on HuggingFace:
GottBERT-based: https://huggingface.co/jfrei/de_GERNERMEDpp_GottBERT
GermanBERT-based: https://huggingface.co/jfrei/de_GERNERMEDpp_GermanBERT
Slim model: https://huggingface.co/jfrei/de_GERNERMEDpp_Slim

Since this model is based on SpaCy and I'm not familiar with NVIDIA's TAO toolkit, this seems quite tricky. For NER, SpaCy applies an iterative entity parsing approach and I'm not sure whether this parsing algorithm can be (re-)implemented in TAO in a straightforward manner, so it's not just a matter of loading the weights.

In case you are not dependent on the NVIDIA platform itself, you might want to wrap the inference process into an HTTP-based service.

Kind regards,
Johann
